// Code generated by Slice Machine. DO NOT EDIT.

import Bento from './Bento/index.svelte';
import Hero from './Hero/index.svelte';
import Locations from './Locations/index.svelte';
import Programs from './Programs/index.svelte';
import RichText from './RichText/index.svelte';
import Showcase from './Showcase/index.svelte';
import Sparkle from './Sparkle/index.svelte';
import Staff from './Staff/index.svelte';

export const components = {
	bento: Bento,
	hero: Hero,
	locations: Locations,
	programs: Programs,
	rich_text: RichText,
	showcase: Showcase,
	sparkle: Sparkle,
	staff: Staff
};
