// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Globals → Navigation*
 */
export interface GlobalsDocumentDataNavigationItem {
	/**
	 * Link field in *Globals → Navigation*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: globals.navigation[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Label field in *Globals → Navigation*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: globals.navigation[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * CTA Button field in *Globals → Navigation*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: globals.navigation[].cta_button
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	cta_button: prismic.BooleanField;

	/**
	 * Role Based  field in *Globals → Navigation*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: globals.navigation[].role_based
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	role_based: prismic.BooleanField;

	/**
	 * Role field in *Globals → Navigation*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: globals.navigation[].role
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	role: prismic.SelectField<'Staff' | 'Admin'>;
}

/**
 * Content for Globals documents
 */
interface GlobalsDocumentData {
	/**
	 * Site Title field in *Globals*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: globals.site_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	site_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Globals*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: globals.meta_description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * OG Image field in *Globals*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: globals.og_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	og_image: prismic.ImageField<never>;

	/**
	 * Navigation field in *Globals*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: globals.navigation[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	navigation: prismic.GroupField<Simplify<GlobalsDocumentDataNavigationItem>>;
}

/**
 * Globals document from Prismic
 *
 * - **API ID**: `globals`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<GlobalsDocumentData>,
	'globals',
	Lang
>;

type LocationDocumentDataSlicesSlice =
	| RichTextSlice
	| SparkleSlice
	| BentoSlice
	| HeroSlice
	| ShowcaseSlice;

/**
 * Content for Location documents
 */
interface LocationDocumentData {
	/**
	 * Heading field in *Location*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: location.heading
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Image field in *Location*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: location.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Description field in *Location*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: location.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Slice Zone field in *Location*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: location.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<LocationDocumentDataSlicesSlice> /**
	 * Meta Title field in *Location*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: location.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Location*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: location.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Location*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: location.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Location document from Prismic
 *
 * - **API ID**: `location`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LocationDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<LocationDocumentData>,
	'location',
	Lang
>;

type PageDocumentDataSlicesSlice =
	| LocationsSlice
	| BentoSlice
	| ProgramsSlice
	| SparkleSlice
	| StaffSlice
	| ShowcaseSlice
	| HeroSlice
	| RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

/**
 * Item in *Program → Links*
 */
export interface ProgramDocumentDataLinksItem {
	/**
	 * Info field in *Program → Links*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: program.links[].info
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	info: prismic.ContentRelationshipField<'current_students'>;
}

type ProgramDocumentDataSlicesSlice = RichTextSlice;

/**
 * Content for Program documents
 */
interface ProgramDocumentData {
	/**
	 * Program Name field in *Program*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: program.program_name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	program_name: prismic.RichTextField;

	/**
	 * Program Tag Line field in *Program*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: program.program_tag_line
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	program_tag_line: prismic.KeyTextField;

	/**
	 * Program Image field in *Program*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: program.program_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	program_image: prismic.ImageField<never>;

	/**
	 * Links field in *Program*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: program.links[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	links: prismic.GroupField<Simplify<ProgramDocumentDataLinksItem>>;

	/**
	 * Slice Zone field in *Program*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: program.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ProgramDocumentDataSlicesSlice> /**
	 * Meta Title field in *Program*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: program.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Program*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: program.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Program*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: program.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Program document from Prismic
 *
 * - **API ID**: `program`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProgramDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<ProgramDocumentData>,
	'program',
	Lang
>;

export type AllDocumentTypes = GlobalsDocument | LocationDocument | PageDocument | ProgramDocument;

/**
 * Item in *Bento → Default → Primary → box*
 */
export interface BentoSliceDefaultPrimaryBoxItem {
	/**
	 * box image field in *Bento → Default → Primary → box*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bento.default.primary.box[].box_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	box_image: prismic.ImageField<never>;

	/**
	 * wide field in *Bento → Default → Primary → box*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: bento.default.primary.box[].wide
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	wide: prismic.BooleanField;

	/**
	 * box title field in *Bento → Default → Primary → box*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bento.default.primary.box[].box_title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	box_title: prismic.RichTextField;

	/**
	 * box body field in *Bento → Default → Primary → box*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bento.default.primary.box[].box_body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	box_body: prismic.RichTextField;
}

/**
 * Primary content in *Bento → Default → Primary*
 */
export interface BentoSliceDefaultPrimary {
	/**
	 * body field in *Bento → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bento.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * box field in *Bento → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bento.default.primary.box[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	box: prismic.GroupField<Simplify<BentoSliceDefaultPrimaryBoxItem>>;
}

/**
 * Default variation for Bento Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BentoSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<BentoSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Bento*
 */
type BentoSliceVariation = BentoSliceDefault;

/**
 * Bento Shared Slice
 *
 * - **API ID**: `bento`
 * - **Description**: Bento
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BentoSlice = prismic.SharedSlice<'bento', BentoSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Tag Line field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.tag_line
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	tag_line: prismic.RichTextField;

	/**
	 * Hero Image field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.hero_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	hero_image: prismic.ImageField<never>;

	/**
	 * Button Link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link: prismic.LinkField;

	/**
	 * Button Label field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.button_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_label: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Item in *Locations → Default → Primary → Location*
 */
export interface LocationsSliceDefaultPrimaryLocationItem {
	/**
	 * Location field in *Locations → Default → Primary → Location*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: locations.default.primary.location[].location
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	location: prismic.ContentRelationshipField<'location'>;
}

/**
 * Primary content in *Locations → Default → Primary*
 */
export interface LocationsSliceDefaultPrimary {
	/**
	 * Heading field in *Locations → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: locations.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * body field in *Locations → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: locations.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Image field in *Locations → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: locations.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Location field in *Locations → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: locations.default.primary.location[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	location: prismic.GroupField<Simplify<LocationsSliceDefaultPrimaryLocationItem>>;
}

/**
 * Default variation for Locations Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LocationsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<LocationsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Locations*
 */
type LocationsSliceVariation = LocationsSliceDefault;

/**
 * Locations Shared Slice
 *
 * - **API ID**: `locations`
 * - **Description**: Locations
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LocationsSlice = prismic.SharedSlice<'locations', LocationsSliceVariation>;

/**
 * Item in *Programs → Default → Primary → Programs*
 */
export interface ProgramsSliceDefaultPrimaryProgramsItem {
	/**
	 * Program field in *Programs → Default → Primary → Programs*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: programs.default.primary.programs[].program
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	program: prismic.ContentRelationshipField<'program'>;
}

/**
 * Primary content in *Programs → Default → Primary*
 */
export interface ProgramsSliceDefaultPrimary {
	/**
	 * Heading field in *Programs → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: programs.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Body field in *Programs → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: programs.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	body: prismic.KeyTextField;

	/**
	 * Programs field in *Programs → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: programs.default.primary.programs[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	programs: prismic.GroupField<Simplify<ProgramsSliceDefaultPrimaryProgramsItem>>;
}

/**
 * Default variation for Programs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProgramsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ProgramsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Programs*
 */
type ProgramsSliceVariation = ProgramsSliceDefault;

/**
 * Programs Shared Slice
 *
 * - **API ID**: `programs`
 * - **Description**: Programs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProgramsSlice = prismic.SharedSlice<'programs', ProgramsSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * Content field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Lorem ipsum...
	 * - **API ID Path**: rich_text.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RichTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>;

/**
 * Item in *Showcase → Default → Primary → Content*
 */
export interface ShowcaseSliceDefaultPrimaryContentItem {
	/**
	 * Title field in *Showcase → Default → Primary → Content*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.default.primary.content[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Body field in *Showcase → Default → Primary → Content*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.default.primary.content[].body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Image field in *Showcase → Default → Primary → Content*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.default.primary.content[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * link field in *Showcase → Default → Primary → Content*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.default.primary.content[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * label field in *Showcase → Default → Primary → Content*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.default.primary.content[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * reverse field in *Showcase → Default → Primary → Content*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: showcase.default.primary.content[].reverse
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	reverse: prismic.BooleanField;
}

/**
 * Primary content in *Showcase → Default → Primary*
 */
export interface ShowcaseSliceDefaultPrimary {
	/**
	 * Heading field in *Showcase → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Content field in *Showcase → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: showcase.default.primary.content[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	content: prismic.GroupField<Simplify<ShowcaseSliceDefaultPrimaryContentItem>>;
}

/**
 * Default variation for Showcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShowcaseSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ShowcaseSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Showcase*
 */
type ShowcaseSliceVariation = ShowcaseSliceDefault;

/**
 * Showcase Shared Slice
 *
 * - **API ID**: `showcase`
 * - **Description**: Showcase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShowcaseSlice = prismic.SharedSlice<'showcase', ShowcaseSliceVariation>;

/**
 * Primary content in *Sparkle → Default → Primary*
 */
export interface SparkleSliceDefaultPrimary {
	/**
	 * Heading field in *Sparkle → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sparkle.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Body field in *Sparkle → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sparkle.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
}

/**
 * Default variation for Sparkle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SparkleSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<SparkleSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Sparkle*
 */
type SparkleSliceVariation = SparkleSliceDefault;

/**
 * Sparkle Shared Slice
 *
 * - **API ID**: `sparkle`
 * - **Description**: Sparkle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SparkleSlice = prismic.SharedSlice<'sparkle', SparkleSliceVariation>;

/**
 * Item in *Staff → Default → Primary → StaffCard*
 */
export interface StaffSliceDefaultPrimaryStaffcardItem {
	/**
	 * Name field in *Staff → Default → Primary → StaffCard*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.default.primary.staffcard[].name
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	name: prismic.RichTextField;

	/**
	 * Title field in *Staff → Default → Primary → StaffCard*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.default.primary.staffcard[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Avatar field in *Staff → Default → Primary → StaffCard*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.default.primary.staffcard[].avatar
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	avatar: prismic.ImageField<never>;
}

/**
 * Primary content in *Staff → Default → Primary*
 */
export interface StaffSliceDefaultPrimary {
	/**
	 * Heading field in *Staff → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * StaffCard field in *Staff → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.default.primary.staffcard[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	staffcard: prismic.GroupField<Simplify<StaffSliceDefaultPrimaryStaffcardItem>>;
}

/**
 * Default variation for Staff Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StaffSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<StaffSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Staff*
 */
type StaffSliceVariation = StaffSliceDefault;

/**
 * Staff Shared Slice
 *
 * - **API ID**: `staff`
 * - **Description**: Staff
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StaffSlice = prismic.SharedSlice<'staff', StaffSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			GlobalsDocument,
			GlobalsDocumentData,
			GlobalsDocumentDataNavigationItem,
			LocationDocument,
			LocationDocumentData,
			LocationDocumentDataSlicesSlice,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			ProgramDocument,
			ProgramDocumentData,
			ProgramDocumentDataLinksItem,
			ProgramDocumentDataSlicesSlice,
			AllDocumentTypes,
			BentoSlice,
			BentoSliceDefaultPrimaryBoxItem,
			BentoSliceDefaultPrimary,
			BentoSliceVariation,
			BentoSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			LocationsSlice,
			LocationsSliceDefaultPrimaryLocationItem,
			LocationsSliceDefaultPrimary,
			LocationsSliceVariation,
			LocationsSliceDefault,
			ProgramsSlice,
			ProgramsSliceDefaultPrimaryProgramsItem,
			ProgramsSliceDefaultPrimary,
			ProgramsSliceVariation,
			ProgramsSliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault,
			ShowcaseSlice,
			ShowcaseSliceDefaultPrimaryContentItem,
			ShowcaseSliceDefaultPrimary,
			ShowcaseSliceVariation,
			ShowcaseSliceDefault,
			SparkleSlice,
			SparkleSliceDefaultPrimary,
			SparkleSliceVariation,
			SparkleSliceDefault,
			StaffSlice,
			StaffSliceDefaultPrimaryStaffcardItem,
			StaffSliceDefaultPrimary,
			StaffSliceVariation,
			StaffSliceDefault
		};
	}
}
